services:
    chessmate-db:
        image: postgres:15-alpine
        container_name: postgres-dev
        restart: always
        ports:
            - 5432:5432
        env_file:
            - ./apps/api/.env
