import { UserProvider } from "../context/UserContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body> <UserProvider>{children}</UserProvider></body>
    </html>
  )
}
